---
amf_as_services: []

amf_as_user_group:
  users:
    - "oracle"
  groups:
    - "dba"

amf_as_paths:
  - "/etc/oratab"
  - "/etc/oraInst.loc"

amf_as_packages: []

amf_as_processes:
  - "ora_mmon_"
  - "ora_pmon_"
  - "ora_smon_"
  - "tnslsnr"

# Returned fields
amf_as_discovered_app:
  name: "Oracle Database"
  desc: "Hosts identified as Oracle Database Servers"
